e2fsck -yf odm.img
resize2fs -M odm.img
e2fsck -yf odm.img
e2fsck -yf optics.img
resize2fs -M optics.img
e2fsck -yf optics.img
e2fsck -yf prism.img
resize2fs -M prism.img
e2fsck -yf prism.img
e2fsck -yf product.img
resize2fs -M product.img
e2fsck -yf product.img
e2fsck -yf system.img
resize2fs -M system.img
e2fsck -yf system.img
e2fsck -yf vendor.img
resize2fs -M vendor.img
e2fsck -yf vendor.img
